name: bacomathiques
description: Cours gratuits pour réviser les maths au lycée !
version: 3.0.2+52
homepage: https://bacomathiqu.es
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.1
  jovial_svg: ^1.1.23
  share_plus: ^10.1.1
  rate_my_app: ^2.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  flutter_layout_grid: ^2.0.7
  flutter_widget_from_html_core: ^0.15.2
  flutter_math_fork: ^0.7.2
  indexed_list_view: ^4.0.0
  google_mobile_ads: ^5.2.0
  flutter_riverpod: ^2.6.1
  html: ^0.15.5
  syntax_highlight: ^0.4.0
  collection: ^1.18.0
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBT
      fonts:
        - asset: assets/fonts/FuturaBT-Medium.ttf
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
    - family: Monaco
      fonts:
        - asset: assets/fonts/Monaco-Regular.ttf
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/languages/
