name: Continuous Delivery

on:
  push:
    branches:
      - main
      - master

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUser: ${{ steps.get-user.outputs.containerUser }}
    steps:
      - id: get-user
        run: echo "containerUser=`id -u`:`id -g`" >> $GITHUB_OUTPUT
  build:
    needs: configure
    runs-on:  ubuntu-latest
    container:
      image: skyost/latex-docker
      options: --user ${{ needs.configure.outputs.containerUser }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6
      - name: Setup Node.js 🏗
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: 'npm'
      - name: Install dependencies 👨🏻‍💻
        run: npm ci
      - name: Generate ⚙️
        run: npm run generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          single-commit: true
